workflows:
  ios-capacitor:
    name: Build iOS Capacitor WebView
    environment:
      vars:
        XCODE_PROJECT: "ios/App/App.xcodeproj"
        SCHEME: "App"
      xcode: latest
      node: latest
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Capacitor iOS Sync
        script: |
          npx cap sync ios
      - name: Build IPA
        script: |
          xcodebuild -project $XCODE_PROJECT \
            -scheme $SCHEME \
            -sdk iphoneos \
            -configuration Release \
            archive -archivePath build/App.xcarchive
          xcodebuild -exportArchive \
            -archivePath build/App.xcarchive \
            -exportOptionsPlist ios/App/exportOptions.plist \
            -exportPath build/ipa
    artifacts:
      - build/ipa/*.ipa
