workflows:
  ios_webview:
    name: Build iOS – Capacitor WebView Test
    environment:
      node: latest
      xcode: latest
      cocoapods: default

    scripts:
      - name: Install dependencies
        script: npm ci

      - name: Capacitor iOS Sync
        script: npx cap sync ios

      - name: Install CocoaPods
        script: cd ios/App && pod install && cd ../..

      - name: Build IPA (Unsigned Test)
        script: |
          xcodebuild \
            -workspace ios/App/App.xcworkspace \
            -scheme App \
            -sdk iphoneos \
            -configuration Release \
            -allowProvisioningUpdates \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            archive -archivePath $CM_BUILD_DIR/App.xcarchive

          xcodebuild \
            -exportArchive \
            -archivePath $CM_BUILD_DIR/App.xcarchive \
            -exportPath $CM_BUILD_DIR/ipa \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            -exportOptionsPlist ios/App/exportOptions.plist


    artifacts:
      - $CM_BUILD_DIR/ipa/*.ipa
