workflows:
  ios-capacitor:
    name: Build iOS Capacitor WebView
    environment:
      vars:
        XCODE_PROJECT: "ios/App/App.xcodeproj"
        SCHEME: "App"
      xcode: latest
      node: latest
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Fix Capacitor permissions
        script: |
          chmod +x node_modules/@capacitor/cli/bin/capacitor
          chmod -R 777 ios/
          npx cap sync ios
      - name: Build IPA
        script: |
          xcodebuild -project ios/App/App.xcodeproj \
            -scheme App \
            -sdk iphoneos \
            -configuration Release \
            archive -archivePath $CM_BUILD_DIR/App.xcarchive
          xcodebuild -exportArchive \
            -archivePath $CM_BUILD_DIR/App.xcarchive \
            -exportPath $CM_BUILD_DIR/ \
            -exportOptionsPlist ios/App/exportOptions.plist
    artifacts:
      - build/ipa/*.ipa
