workflows:
  ios_webview:
    name: Build iOS – Capacitor WebView Test
    environment:
      node: latest
      xcode: latest
      cocoapods: default

    scripts:
      - name: Install dependencies
        script: npm ci

      - name: Capacitor iOS Sync
        script: npx cap sync ios

      - name: Install CocoaPods
        script: cd ios/App && pod install && cd ../..

      - name: Build IPA (Unsigned Test)
        script: |
          export CODE_SIGNING_ALLOWED=NO
          export CODE_SIGNING_REQUIRED=NO
          export CODE_SIGNING_IDENTITY=""

          xcodebuild \
            -workspace ios/App/App.xcworkspace \
            -scheme App \
            -sdk iphoneos \
            -configuration Release \
            -destination generic/platform=iOS \
            CODE_SIGNING_REQUIRED=$CODE_SIGNING_REQUIRED \
            CODE_SIGNING_ALLOWED=$CODE_SIGNING_ALLOWED \
            CODE_SIGNING_IDENTITY="$CODE_SIGNING_IDENTITY" \
            archive -archivePath $CM_BUILD_DIR/App.xcarchive

          xcodebuild \
            -exportArchive \
            -archivePath $CM_BUILD_DIR/App.xcarchive \
            -exportPath $CM_BUILD_DIR/ipa \
            -exportOptionsPlist ios/App/ExportOptions.plist \
            CODE_SIGNING_ALLOWED=$CODE_SIGNING_ALLOWED \
            CODE_SIGNING_REQUIRED=$CODE_SIGNING_REQUIRED \
            CODE_SIGNING_IDENTITY="$CODE_SIGNING_IDENTITY"

    artifacts:
      - $CM_BUILD_DIR/ipa/*.ipa
