workflows:
  build_ios:
    name: Build iOS WebView Capacitor
    environment:
      node: latest
      xcode: latest
      cocoapods: default

    scripts:
      - name: Instalar dependências do projeto
        script: npm ci

      - name: Sincronizar Capacitor iOS
        script: |
          npx cap sync ios
          
      - name: Instalar Pods iOS
        script: |
          cd ios/App && pod install && cd ../..

      - name: Gerar IPA iOS
        script: |
          cd ios/App
          xcodebuild \
            -workspace App.xcworkspace \
            -scheme App \
            -sdk iphoneos \
            -configuration Release \
            -allowProvisioningUpdates \
            archive -archivePath $CM_BUILD_DIR/app.xcarchive

          xcodebuild \
            -exportArchive \
            -archivePath $CM_BUILD_DIR/app.xcarchive \
            -exportPath $CM_BUILD_DIR/ipa \
            -exportOptionsPlist ExportOptions.plist

    artifacts:
      - $CM_BUILD_DIR/ipa/*.ipa
