workflows:
  ios_webview:
    name: Build iOS + Android – Capacitor Test

    environment:
      node: latest
      xcode: latest
      cocoapods: default
      java: 17

    scripts:
      - name: Install dependencies
        script: npm ci

      - name: Capacitor Sync (iOS + Android)
        script: |
          npx cap sync ios
          npx cap sync android

      - name: Install CocoaPods
        script: |
          cd ios/App
          pod install
          cd ../..

      - name: Build APK Debug
        script: |
          cd android
          ./gradlew assembleDebug

      - name: Build IPA (Unsigned Test)
        script: |
          set -e
          export CODE_SIGNING_ALLOWED=NO
          export CODE_SIGNING_REQUIRED=NO
          export CODE_SIGNING_IDENTITY=""

          ARCHIVE_PATH="$CM_BUILD_DIR/App.xcarchive"
          IPA_DIR="$CM_BUILD_DIR/ipa"
          PAYLOAD_DIR="$CM_BUILD_DIR/Payload"

          xcodebuild \
            -workspace ios/App/App.xcworkspace \
            -scheme App \
            -sdk iphoneos \
            -configuration Release \
            -destination generic/platform=iOS \
            CODE_SIGNING_REQUIRED=$CODE_SIGNING_REQUIRED \
            CODE_SIGNING_ALLOWED=$CODE_SIGNING_ALLOWED \
            CODE_SIGNING_IDENTITY="$CODE_SIGNING_IDENTITY" \
            archive -archivePath "$ARCHIVE_PATH"

          rm -rf "$IPA_DIR" "$PAYLOAD_DIR"
          mkdir -p "$IPA_DIR" "$PAYLOAD_DIR"

          cp -R "$ARCHIVE_PATH/Products/Applications/App.app" "$PAYLOAD_DIR/"
          cd "$CM_BUILD_DIR"
          /usr/bin/zip -r "$IPA_DIR/App-unsigned.ipa" Payload
          rm -rf "$PAYLOAD_DIR"

    artifacts:
      - android/app/build/outputs/apk/debug/*.apk
      - $CM_BUILD_DIR/ipa/*.ipa
