workflows:
  ios_webview:
    name: Build iOS WebView Capacitor Only
    environment:
      node: latest
      xcode: latest
      cocoapods: default

    scripts:
      - name: Install dependencies
        script: npm ci

      - name: Capacitor iOS Sync
        script: npx cap sync ios

      - name: Build IPA (Unsigned Test)
        script: |
          cd ios/App/App
          xcodebuild \
            -project App.xcodeproj \
            -scheme App \
            -sdk iphoneos \
            -configuration Release \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            archive -archivePath $CM_BUILD_DIR/App.xcarchive

          xcodebuild \
            -exportArchive \
            -archivePath $CM_BUILD_DIR/App.xcarchive \
            -exportPath $CM_BUILD_DIR/ipa \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            -exportOptionsPlist ios/App/exportOptions.plist

    artifacts:
      - $CM_BUILD_DIR/ipa/*.ipa
